# Generated by Django 5.1 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mac_devices', to='vouchers.internetplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_devices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'iot_macdevice',
                'ordering': ['-created_at'],
            },
        ),
    ]
