# Generated by Django 5.2.17 on 2026-09-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0001_initial'),
        ('routers', '0005_router_hardware_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='macdevice',
            name='access_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('timed', 'Time limited')], default='timed', max_length=16),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_devices', to='routers.nasdevice'),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='vlan_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
