# Generated by Django 5.2.17 on 2026-09-15 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_registrations(apps, schema_editor):
    import re
    Device = apps.get_model('iot_devices', 'MacDevice')
    rows = Device.objects.using(schema_editor.connection.alias)
    active = {}
    for device in rows.order_by('pk').iterator():
        compact = re.sub(r'[:.\-\s]', '', device.mac_address).upper()
        if (not re.fullmatch(r'[0-9A-F]{12}', compact) or compact in ('000000000000', 'FFFFFFFFFFFF')
                or int(compact[:2], 16) & 1):
            raise RuntimeError(f'Invalid historical MAC on device ID {device.pk}; reconcile before migration.')
        if device.is_active and compact in active:
            raise RuntimeError(f'Active MAC collision between device IDs {active[compact]} and {device.pk}; reconcile before migration.')
        if device.is_active:
            active[compact] = device.pk
        # Preserve the original stored MAC and rights; populate only new metadata.
        rows.filter(pk=device.pk).update(mac_address_compact=compact,
            status='active' if device.is_active else 'suspended')


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0002_macdevice_access_type_macdevice_description_and_more'),
        ('routers', '0005_router_hardware_profile'),
        ('tenants', '0004_agent_funding_fees'),
        ('vouchers', '0008_paymenttransaction_customer_voucher_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_expiry', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('terms', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='macdevice',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='macdevice',
            name='data_limit_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='issued_terms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='legacy_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='mac_address_compact',
            field=models.CharField(blank=True, db_default='', default='', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='speed_limit',
            field=models.CharField(blank=True, db_default='', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('active', 'active'), ('suspended', 'suspended'), ('expired', 'expired'), ('revoked', 'revoked'), ('deleted', 'deleted')], db_default='', default='', max_length=12),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='version',
            field=models.PositiveIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='mac_address',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_devices', to='vouchers.internetplan'),
        ),
        migrations.AddIndex(model_name='macdevice', index=models.Index(fields=['tenant', 'mac_address_compact'], name='iot_tenant_mac_idx')),
        migrations.RunPython(preserve_registrations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='macdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('mac_address_compact', ''), _negated=True)), fields=('mac_address_compact',), name='iot_active_mac_unique'),
        ),
        migrations.AddField(
            model_name='devicerenewal',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicerenewal',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='iot_devices.macdevice'),
        ),
        migrations.AddField(
            model_name='devicerenewal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
    ]
