# Generated by Django 5.2.17 on 2026-09-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0003_devicerenewal_alter_macdevice_options_and_more'),
        ('routers', '0005_router_hardware_profile'),
        ('tenants', '0004_agent_funding_fees'),
        ('vouchers', '0008_paymenttransaction_customer_voucher_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerenewal',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_grant', to='vouchers.paymenttransaction'),
        ),
        migrations.CreateModel(
            name='PublicIoTPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=17)),
                ('expected_version', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_secret_encrypted', models.TextField(editable=False)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='iot_devices.macdevice')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='iot_purchase', to='vouchers.paymenttransaction')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routers.nasdevice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('expected_version__isnull', True)), fields=('mac_address',), name='iot_first_purchase_mac_unique'), models.UniqueConstraint(condition=models.Q(('expected_version__isnull', False)), fields=('device', 'expected_version'), name='iot_renewal_version_unique')],
            },
        ),
    ]
