# Generated by Django 5.2.17 on 2026-09-09 05:38

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['tenant', 'archived_at', 'id'], name='customer_tenant_archive_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('reference'), models.F('tenant'), name='customer_tenant_reference_ci')],
            },
        ),
    ]
