# Generated by Django 5.2.17 on 2026-09-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('routers', '0005_router_hardware_profile'),
        ('tenants', '0001_initial'),
        ('vouchers', '0003_bandwidth_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPPoEPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_hours', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(help_text='NGN kobo; manual renewal does not record a payment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bandwidth_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pppoe_plans', to='vouchers.bandwidthprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pppoe_plans', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PPPoEService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('rate_limit', models.CharField(max_length=30)),
                ('period_hours', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('suspended', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('disconnect_before', models.DateTimeField(blank=True, null=True)),
                ('disconnect_state', models.CharField(choices=[('not_checked', 'Not checked'), ('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('clear', 'Clear'), ('failed', 'Failed')], default='not_checked', max_length=20)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pppoe_service', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='customers.pppoeplan')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pppoe_services', to='routers.nasdevice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pppoe_services', to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pppoeplan',
            constraint=models.CheckConstraint(condition=models.Q(('duration_hours__gte', 1), ('duration_hours__lte', 8760)), name='pppoe_plan_duration_range'),
        ),
        migrations.AddIndex(
            model_name='pppoeservice',
            index=models.Index(fields=['lease_until', 'last_reconciled_at'], name='pppoe_reconcile_idx'),
        ),
    ]
