# Generated by Django 5.2.17 on 2026-09-11 12:08

import django.db.models.deletion
from django.db import migrations, models


def add_accounting_mac(apps, schema_editor):
    connection = schema_editor.connection
    if "radacct" not in connection.introspection.table_names():
        return  # FreeRADIUS owns this table; its installation must include Calling-Station-Id.
    with connection.cursor() as cursor:
        columns = {field.name for field in connection.introspection.get_table_description(cursor, "radacct")}
    if "callingstationid" not in columns:
        schema_editor.execute('ALTER TABLE radacct ADD COLUMN callingstationid varchar(64) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_pppoeplan_pppoeservice_and_more'),
        ('tenants', '0001_initial'),
        ('vouchers', '0004_paymenttransaction_purchased_terms_and_more'),
    ]

    operations = [
        migrations.RunPython(add_accounting_mac, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DeviceAccessSync',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(null=True)),
                ('missing_mac_rows', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('router_name', models.CharField(blank=True, max_length=200)),
                ('nas_address', models.GenericIPAddressField()),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(null=True)),
                ('bytes_in', models.PositiveBigIntegerField(default=0)),
                ('bytes_out', models.PositiveBigIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vouchers.voucher')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'mac_address', 'voucher'], name='device_access_mac_code_idx'), models.Index(fields=['tenant', 'last_seen_at'], name='device_access_seen_idx')],
            },
        ),
    ]
