# Generated by Django 5.2.17 on 2026-09-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_deviceaccesssync_deviceaccesssession'),
        ('tenants', '0004_agent_funding_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='legacy_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='legacy_source',
            field=models.CharField(blank=True, db_default='', default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='mac_address',
            field=models.CharField(blank=True, db_default='', default='', help_text='Contact evidence only; does not grant network access or identify a person.', max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False), models.Q(('legacy_source', ''), _negated=True)), fields=('tenant', 'legacy_source', 'legacy_id'), name='customer_legacy_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('legacy_id__isnull', True), ('legacy_source', '')), models.Q(models.Q(('legacy_source', ''), _negated=True), ('legacy_id__isnull', False)), _connector='OR'), name='customer_legacy_identity_pair'),
        ),
    ]
