# Generated by Django 5.2.17 on 2026-09-07 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F
from django.utils import timezone as timezone


def stamp_existing_users_verified(apps, schema_editor):
    """Accounts that already exist were created through trusted flows — treat
    them as verified so the new OTP gate never locks out current users."""
    apps.get_model("accounts", "User").objects.filter(email_verified_at__isnull=True).update(
        email_verified_at=F("date_joined")
    )


def unstamp(apps, schema_editor):
    apps.get_model("accounts", "User").objects.update(email_verified_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_unique_user_email_casefold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, default=timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_email_verification_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_em_user_id_22e400_idx')],
            },
        ),
        migrations.RunPython(stamp_existing_users_verified, unstamp),
    ]
