# Generated by Django 5.2.17 on 2026-09-08 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified_at_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEmailChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('token_hash', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_registration_email_challenge',
                'indexes': [models.Index(fields=['expires_at'], name='registration_expiry_idx')],
            },
        ),
    ]
