# Generated by Django 5.2.17 on 2026-09-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('vouchers', '0002_paymenttransaction_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='rate_limit_snapshot',
            field=models.CharField(blank=True, db_default='', default='', max_length=20),
        ),
        migrations.CreateModel(
            name='BandwidthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload_kbps', models.PositiveIntegerField()),
                ('download_kbps', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_profiles', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='internetplan',
            name='bandwidth_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='vouchers.bandwidthprofile'),
        ),
        migrations.AddConstraint(
            model_name='bandwidthprofile',
            constraint=models.CheckConstraint(condition=models.Q(('upload_kbps__gte', 1), ('upload_kbps__lte', 10000000)), name='bandwidth_upload_range'),
        ),
        migrations.AddConstraint(
            model_name='bandwidthprofile',
            constraint=models.CheckConstraint(condition=models.Q(('download_kbps__gte', 1), ('download_kbps__lte', 10000000)), name='bandwidth_download_range'),
        ),
    ]
