# Generated by Django 5.2.17 on 2026-09-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_bandwidth_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='purchased_terms',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='purchased_terms',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vouchers.internetplan'),
        ),
    ]
