# Generated by Django 5.2.17 on 2026-09-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0005_router_hardware_profile'),
        ('tenants', '0002_identity_compatibility'),
        ('vouchers', '0004_paymenttransaction_purchased_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='agent_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='is_public',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='plan_type',
            field=models.CharField(choices=[('voucher', 'Hotspot voucher'), ('iot_mac', 'IoT / MAC')], db_default='voucher', default='voucher', max_length=20),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='public_router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_internet_plans', to='routers.nasdevice'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='issued_duration_seconds',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='duration_hours',
            field=models.DecimalField(decimal_places=6, help_text='Hours; rounded to whole seconds at issuance', max_digits=16),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='rate_limit',
            field=models.CharField(blank=True, default='', help_text='e.g., 5M/10M (up/down)', max_length=50),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='rate_limit_snapshot',
            field=models.CharField(blank=True, db_default='', default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='internetplan',
            constraint=models.CheckConstraint(condition=models.Q(('archived_at__isnull', True), models.Q(('agent_enabled', False), ('is_active', False), ('is_public', False)), _connector='OR'), name='archived_plan_not_sellable'),
        ),
    ]
