# Generated by Django 5.2.17 on 2026-09-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0005_router_hardware_profile'),
        ('vouchers', '0005_customer_plan_compatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='bound_device_mac',
            field=models.CharField(blank=True, editable=False, max_length=17),
        ),
        migrations.AddField(
            model_name='voucher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='device_bound_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='device_bound_nas',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bound_vouchers', to='routers.nasdevice'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='device_lock_enabled',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='first_used_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_used',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='last_used_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='legacy_provenance',
            field=models.JSONField(blank=True, editable=False, help_text='Import source IDs and retained usage, binding-reset and deletion audit evidence. Not exposed by API.', null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('unused', 'Unused'), ('sold', 'Sold'), ('used', 'Used'), ('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='unused', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
