# Generated by Django 5.2.17 on 2026-09-14 16:10

import django.db.models.functions.text
from django.db import migrations, models


def check_existing_identities(apps, schema_editor):
    Voucher = apps.get_model('vouchers', 'Voucher')
    duplicates = Voucher.objects.using(schema_editor.connection.alias).order_by().annotate(
        identity=django.db.models.functions.text.Lower('username')).values('identity').annotate(
        total=models.Count('id')).filter(total__gt=1)
    if duplicates.exists():
        raise RuntimeError('Conflicting voucher identities require review. Run audit_voucher_code_identities; existing credentials will not be renamed.')


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('routers', '0005_router_hardware_profile'),
        ('tenants', '0003_voucher_code_formats'),
        ('vouchers', '0006_voucher_lifecycle_preservation'),
    ]

    operations = [
        migrations.RunPython(check_existing_identities, migrations.RunPython.noop),
        migrations.AddField(
            model_name='internetplan',
            name='voucher_code_format',
            field=models.CharField(choices=[('tenant_default', 'Business default'), ('legacy', 'Readable mixed (existing)'), ('numeric', 'Numbers only'), ('alphabetic', 'Letters only'), ('alphanumeric', 'Letters and numbers')], default='legacy', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='voucher_username_casefold_unique'),
        ),
    ]
