# Generated by Django 5.2.17 on 2026-09-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_legacy_id_customer_legacy_source_and_more'),
        ('vouchers', '0007_voucher_code_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='customers.customer'),
        ),
    ]
