# Generated by Django 5.2.17 on 2026-09-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_digest', models.CharField(max_length=64, unique=True)),
                ('plan_digest', models.CharField(max_length=64)),
                ('completed_at', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LegacyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=200)),
                ('source_digest', models.CharField(max_length=64)),
                ('payload_encrypted', models.TextField(editable=False)),
                ('targets', models.JSONField(default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.legacyimportrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'source_key'), name='legacy_import_source_unique')],
            },
        ),
    ]
