# Generated by Django 5.2.17 on 2026-09-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
