# Generated by Django 5.2.17 on 2026-09-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_identity_compatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsetting',
            name='default_voucher_code_format',
            field=models.CharField(choices=[('legacy', 'Readable mixed (existing)'), ('numeric', 'Numbers only'), ('alphabetic', 'Letters only'), ('alphanumeric', 'Letters and numbers')], default='legacy', max_length=20),
        ),
    ]
