# Generated by Django 5.2.17 on 2026-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_voucher_code_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsetting',
            name='agent_funding_fee_percent',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenantsetting',
            name='agent_funding_flat_fee',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
