# Generated by Django 5.2.17 on 2026-09-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_payment_purchase_target'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='plan_terms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_voucher_print_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_routers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('terms', models.JSONField()),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='period', to='subscriptions.subscriptionpayment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='subscriptions.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_periods', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'starts_at', 'ends_at'], name='subscription_period_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='subscription_period_positive')],
            },
        ),
        migrations.CreateModel(
            name='VoucherPrintAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.PositiveBigIntegerField()),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'day', 'voucher_id'), name='unique_daily_voucher_print')],
            },
        ),
    ]
