# Generated by Django 5.2.17 on 2026-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_backfill_purchased_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionperiod',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
    ]
