# Generated by Django 5.1 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWhatsAppRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=100)),
                ('access_token_encrypted', models.CharField(max_length=500)),
                ('webhook_token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_route', to='tenants.tenant')),
            ],
            options={
                'db_table': 'whatsapp_tenantwhatsapproute',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSenderBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_bindings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'whatsapp_senderbinding',
                'unique_together': {('phone_number',)},
            },
        ),
    ]
