# Generated by Django 5.2.17 on 2026-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantwhatsapproute',
            name='access_token_encrypted',
            field=models.TextField(),
        ),
    ]
