# Generated by Django 5.2.17 on 2026-09-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_routing', '0002_alter_tenantwhatsapproute_access_token_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantwhatsapproute',
            name='display_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
    ]
