# Generated by Django 5.2.17 on 2026-09-15 04:39

import apps.whatsapp_routing.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_agent_funding_fees'),
        ('whatsapp_routing', '0003_tenantwhatsapproute_display_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWhatsAppEndpoint',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(max_length=100)),
                ('display_number', models.CharField(max_length=16)),
                ('access_token_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('version', models.UUIDField(default=uuid.uuid4)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('hash_key_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='wa_shared_endpoint_singleton')],
            },
        ),
        migrations.CreateModel(
            name='TenantWhatsAppEntryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(default=apps.whatsapp_routing.models.new_entry_selector, max_length=64, unique=True)),
                ('version', models.UUIDField(default=uuid.uuid4)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_entry_route', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppRoutedSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_hash', models.CharField(max_length=64)),
                ('version', models.UUIDField(default=uuid.uuid4)),
                ('endpoint_version', models.UUIDField()),
                ('route_selector', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.sharedwhatsappendpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.tenantwhatsappentryroute')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppRoutingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_version', models.UUIDField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_holds', to='whatsapp_routing.whatsapproutedsender')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='whatsapproutedsender',
            constraint=models.UniqueConstraint(fields=('endpoint', 'customer_hash'), name='wa_endpoint_customer_unique'),
        ),
    ]
