# Generated by Django 5.2.17 on 2026-09-15 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_agent_funding_fees'),
        ('whatsapp_routing', '0004_sharedwhatsappendpoint_tenantwhatsappentryroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=100)),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('message_id', models.CharField(max_length=512)),
                ('kind', models.CharField(max_length=10)),
                ('provider_timestamp', models.PositiveBigIntegerField()),
                ('customer_hash', models.CharField(max_length=64)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('payload_encrypted', models.TextField()),
                ('endpoint_version', models.UUIDField()),
                ('binding_version', models.UUIDField(null=True)),
                ('state', models.CharField(choices=[('ready', 'ready'), ('blocked', 'blocked'), ('stale', 'stale'), ('unsupported', 'unsupported'), ('status', 'status'), ('conflict', 'conflict')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('binding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.whatsapproutedsender')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.sharedwhatsappendpoint')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'received_at'], name='wa_inbox_state_received')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSenderWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=100)),
                ('customer_hash', models.CharField(max_length=64)),
                ('provider_timestamp', models.PositiveBigIntegerField(default=0)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.sharedwhatsappendpoint')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'phone_number_id', 'customer_hash'), name='wa_sender_watermark_unique')],
            },
        ),
    ]
