# Generated by Django 5.2.17 on 2026-09-15 05:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_agent_funding_fees'),
        ('vouchers', '0007_voucher_code_formats'),
        ('whatsapp_routing', '0005_whatsappinboundevent_whatsappsenderwatermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedwhatsappendpoint',
            name='verification_attempt',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='tenantwhatsappentryroute',
            name='reminder_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_event_timestamp', models.PositiveBigIntegerField(default=0)),
                ('binding_version', models.UUIDField()),
                ('state', models.CharField(default='menu', max_length=20)),
                ('menu', models.JSONField(default=list)),
                ('menu_offset', models.PositiveIntegerField(default=0)),
                ('selected_terms', models.JSONField(null=True)),
                ('reminders_opt_in', models.BooleanField(default=False)),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.whatsapproutedsender')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_reminder_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('endpoint_version', models.UUIDField()),
                ('phone_number_id', models.CharField(max_length=100)),
                ('customer_hash', models.CharField(max_length=64)),
                ('recipient_encrypted', models.TextField()),
                ('payment_secret_encrypted', models.TextField()),
                ('state', models.CharField(default='new', max_length=20)),
                ('checkout_encrypted', models.TextField(blank=True)),
                ('claim', models.UUIDField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('next_check_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('reminders_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.whatsappconversation')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.sharedwhatsappendpoint')),
                ('hold', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.whatsapproutinghold')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_order', to='vouchers.paymenttransaction')),
                ('source_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.whatsappinboundevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppOutbound',
            fields=[
                ('context', models.JSONField(default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedup_key', models.CharField(max_length=160, unique=True)),
                ('endpoint_version', models.UUIDField()),
                ('phone_number_id', models.CharField(max_length=100)),
                ('customer_hash', models.CharField(max_length=64)),
                ('binding_version', models.UUIDField(null=True)),
                ('kind', models.CharField(default='reply', max_length=24)),
                ('payload_encrypted', models.TextField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=512)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claim', models.UUIDField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.sharedwhatsappendpoint')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound', to='whatsapp_routing.whatsapporder')),
                ('source_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='whatsapp_routing.whatsappinboundevent')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='processing', to='whatsapp_routing.whatsappinboundevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='whatsapporder',
            index=models.Index(fields=['state', 'next_check_at'], name='wa_order_state_check'),
        ),
        migrations.AddIndex(
            model_name='whatsappoutbound',
            index=models.Index(fields=['state', 'next_attempt_at'], name='wa_outbox_state_attempt'),
        ),
    ]
