# Generated by Django 5.2.17 on 2026-09-05 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('vouchers', '0002_paymenttransaction_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='vouchers.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'sending'])), fields=('payment',), name='one_live_payment_delivery')],
            },
        ),
    ]
