# Generated by Django 5.1 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentvoucherallocation',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_allocation', to='vouchers.voucher'),
        ),
        migrations.AddField(
            model_name='agentwallet',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='agents.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentwalletfundingpayment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_payments', to='agents.agentwallet'),
        ),
    ]
