# Generated by Django 5.2.17 on 2026-09-15 02:52

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('vouchers', '0007_voucher_code_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentvoucherallocation',
            name='commission_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agentvoucherallocation',
            name='retail_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentvoucherallocation',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agent_allocation', to='vouchers.voucher'),
        ),
        migrations.CreateModel(
            name='AgentWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('voucher_sale', 'Voucher sale'), ('funding', 'Wallet funding')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('previous_balance', models.PositiveIntegerField()),
                ('new_balance', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='agents.agentwallet')),
            ],
            options={
                'db_table': 'agents_wallettransaction',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='agentvoucherallocation',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='agents.agentwallettransaction'),
        ),
        migrations.AddField(
            model_name='agentwalletfundingpayment',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_payment', to='agents.agentwallettransaction'),
        ),
        migrations.AddIndex(
            model_name='agentwallettransaction',
            index=models.Index(fields=['wallet', '-created_at', '-id'], name='agent_wallet_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentwallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', 'voucher_sale'), ('previous_balance', django.db.models.expressions.CombinedExpression(models.F('new_balance'), '+', models.F('amount')))), models.Q(('category', 'funding'), ('new_balance', django.db.models.expressions.CombinedExpression(models.F('previous_balance'), '+', models.F('amount')))), _connector='OR'), name='agent_wallet_movement_arithmetic'),
        ),
    ]
