# Generated by Django 5.2.17 on 2026-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_wallet_movements_and_commission_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentwalletfundingpayment',
            name='funding_terms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
