# Generated by Django 5.2.17 on 2026-09-15 03:42

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_funding_fees'),
        ('tenants', '0004_agent_funding_fees'),
        ('vouchers', '0007_voucher_code_formats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCreditBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('retail_price', models.PositiveIntegerField()),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.PositiveIntegerField()),
                ('repaid', models.PositiveIntegerField(default=0)),
                ('cancelled_debt', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=200)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_batches', to='agents.agentprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vouchers.internetplan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='agentvoucherallocation',
            name='credit_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_allocations', to='agents.agentcreditbatch'),
        ),
        migrations.CreateModel(
            name='AgentCreditMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issue', 'Issue'), ('repay', 'Repayment'), ('reverse', 'Reversal')], max_length=12)),
                ('request_key', models.UUIDField()),
                ('request_payload', models.JSONField()),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('previous_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='agents.agentcreditbatch')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='agents.agentcreditledger')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentcreditbatch',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='credit_batch_total'),
        ),
        migrations.AddConstraint(
            model_name='agentcreditbatch',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', django.db.models.expressions.CombinedExpression(models.F('repaid'), '+', models.F('cancelled_debt')))), name='credit_batch_settlement'),
        ),
        migrations.AddConstraint(
            model_name='agentcreditbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 100)), name='credit_batch_quantity'),
        ),
        migrations.AddConstraint(
            model_name='agentcreditmovement',
            constraint=models.UniqueConstraint(fields=('tenant', 'request_key'), name='credit_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='agentcreditmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('tenant', 'external_reference'), name='credit_receipt_reference_unique'),
        ),
    ]
