# Generated by Django 5.1 on 2026-09-04 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('nas_secret', models.CharField(max_length=255)),
                ('wireguard_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('wireguard_public_key', models.CharField(blank=True, max_length=255)),
                ('wireguard_port', models.PositiveIntegerField(default=51820)),
                ('routeros_username', models.CharField(blank=True, max_length=100)),
                ('routeros_password_encrypted', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('onboarding_state', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('waiting_for_vpn', 'Waiting for VPN'), ('vpn_failed', 'VPN Failed'), ('testing_radius', 'Testing RADIUS'), ('radius_failed', 'RADIUS Failed'), ('accounting_failed', 'Accounting Failed'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=30)),
                ('deployment_status', models.CharField(choices=[('not_deployed', 'Not Deployed'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='not_deployed', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'routers_nasdevice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningAgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('key_id', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routers.nasdevice')),
            ],
            options={
                'db_table': 'routers_provisioningrequest',
            },
        ),
        migrations.CreateModel(
            name='RouterAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('from_state', models.CharField(blank=True, max_length=30, null=True)),
                ('to_state', models.CharField(blank=True, max_length=30, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='routers.nasdevice')),
            ],
            options={
                'db_table': 'routers_auditevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouterOnboardingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('ping', 'Ping'), ('routeros_api', 'RouterOS API'), ('wireguard_peer', 'WireGuard Peer'), ('radius_auth', 'RADIUS Auth'), ('radius_acct', 'RADIUS Accounting'), ('firewall', 'Firewall Rules')], max_length=30)),
                ('passed', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checks', to='routers.nasdevice')),
            ],
            options={
                'db_table': 'routers_onboardingcheck',
                'unique_together': {('router', 'check_type')},
            },
        ),
    ]
