# Generated by Django 5.1 on 2026-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nasdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('wireguard_ip__isnull', False)), fields=('wireguard_ip',), name='unique_router_wireguard_ip'),
        ),
        migrations.AddConstraint(
            model_name='nasdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('wireguard_public_key', ''), _negated=True), fields=('wireguard_public_key',), name='unique_router_wireguard_public_key'),
        ),
    ]
