# Generated by Django 5.2.17 on 2026-09-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_nasdevice_unique_router_wireguard_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdevice',
            name='nas_secret',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nasdevice',
            name='routeros_password_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
