# Generated by Django 5.2.17 on 2026-09-05 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_alter_nasdevice_nas_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('lease_until', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='routers.nasdevice')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('router',), name='one_live_router_operation')],
            },
        ),
    ]
