# Generated by Django 5.2.17 on 2026-09-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0004_routeroperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdevice',
            name='model',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='routeros_version',
            field=models.CharField(blank=True, db_default='', default='', max_length=40),
        ),
    ]
